jobs: 250
default-resources:
  - slurm_partition="short"
  - tasks=1
  - cpus_per_task=1
  - mem_mb=5000
  - runtime=480
  - slurm_account="ag_ukihg_ludwig"
executor: "slurm"
conda-frontend: "conda"
latency-wait: 60
