---
input_plink: "../input_files/prepared_fin.fam"
location_1000G: "resources/1000G/"
contigs_wo_X:
 - 1
genome_ref:
    version: b37
CR_filters:
    variant_CR1: 0.05
    sample_CR1: 0.02
    variant_CR2: 0.02
pca_1000G:
    bcf_maf: 0.05
    pca_maf: 0.10
    window_size: 50
    window_shift: 5
    r2: 1.5

pca_filters_eur:
  pc1_min: -0.01
  pc1_max: -0.005
  pc2_min: -0.017
  pc2_max: -0.0128
